# Generated by Django 4.1.6 on 2023-02-07 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('market_price', models.CharField(max_length=255)),
                ('listed_shares', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.RemoveField(
            model_name='broker',
            name='id',
        ),
        migrations.AlterField(
            model_name='broker',
            name='broker_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_shares', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.broker')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.stock')),
            ],
            options={
                'db_table': 'holdings',
            },
        ),
    ]
