# Generated by Django 4.1.6 on 2023-02-08 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_remove_stock_id_alter_stock_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdings',
            name='stock',
        ),
    ]
