# Generated by Django 4.1.6 on 2023-02-08 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_remove_holdings_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdings',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stockapp.stock'),
            preserve_default=False,
        ),
    ]
