# Generated by Django 4.1.6 on 2023-03-03 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0007_alter_broker_broker_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_shares', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.broker')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.stock')),
            ],
            options={
                'db_table': 'dailytransaction',
            },
        ),
    ]
