# Generated by Django 4.1.6 on 2023-03-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0009_yesterdaytransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yesterdaytransaction',
            name='percentage',
            field=models.IntegerField(),
        ),
    ]
