# Generated by Django 4.1.6 on 2023-03-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0010_alter_yesterdaytransaction_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yesterdaytransaction',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
